M48
; DRILL file {KiCad 7.0.11} date Wed Aug 14 14:49:56 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-14T14:49:56+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X114.44Y-93.52
X114.44Y-102.06
X140.64Y-93.52
X170.04Y-102.06
M30
